# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'BusTicket' do
  # Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

  # Pods for BusTicket
  pod 'ALBusSeatView'
  pod 'iOSDropDown'
  pod 'lottie-ios'
  #pod 'DropDown'
end
